version: "2.1"

services:

  hxlpreview:
    build: ./hxlpreview-dev/
    hostname: hxlpreview
    ports:
      - "4201:4202"
    volumes:
    # adapt to point to the app folder on the host
      - "/home/USER/PROJECTS/hdx-hxl-preview:/srv/hxlpreview"

    entrypoint: "tail -f /dev/null"
